[phases.build]
cmds = [
  "npm install --prefix server",
  "npm install --prefix client",
  "npm run build --prefix client"
]

[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc"]

[start]
cmd = "node server/server.js"
